---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint .
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
provisioner:
  name: ansible
verifier:
  name: ansible
